name: my_flutter_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ðŸ”¥ Firebase dependencies
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.3
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.2.1
  firebase_storage: ^12.4.10
  file_picker: ^10.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/intro1.png
    - assets/intro2.png
    - assets/intro3.png
    - assets/intro4.png
    - assets/intro.png
    - assets/f.png
    - assets/g.png
